version: "3"

volumes:
  data:
    driver: local

networks:
  default:
    driver: bridge

services:
  pdf:
    image: sysnetcz/pdf
    build: .
    container_name: pdf
    restart: always
    ports:
      - "127.0.0.1:8081:8080"
    environment:
     - TZ=Europe/Prague
    volumes:
       - data:/usr/local/data
    networks:
      default:
         aliases:
          - pdf
          - pdf-service
